defmodule CatatanBackend.ApiKey.ParseTest do
  use ExUnit.Case, async: true

  alias CatatanBackend.ApiKey.Parse

  describe "parse/1 - valid inputs" do
    test "parses valid API key with format catatan_id:key" do
      api_key = "catatan_user123:abc456def"

      assert {:ok, %Parse{id: "user123", key: "abc456def"}} = Parse.parse(api_key)
    end

    test "parses API key with special characters in id and key" do
      api_key = "catatan_user@123!#:key$%^&*()"

      assert {:ok, %Parse{id: "user@123!#", key: "key$%^&*()"}} = Parse.parse(api_key)
    end

    test "parses API key with numeric id" do
      api_key = "catatan_12345:abcdef"

      assert {:ok, %Parse{id: "12345", key: "abcdef"}} = Parse.parse(api_key)
    end

    test "parses API key with empty id and key" do
      api_key = "catatan_:"

      assert {:error, :invalid_format} = Parse.parse(api_key)
    end

    test "parses API key with underscores in id and key" do
      api_key = "catatan_user_id_123:key_with_underscores"

      assert {:ok, %Parse{id: "user_id_123", key: "key_with_underscores"}} =
               Parse.parse(api_key)
    end

    test "parses API key with multiple colons (only splits on first colon)" do
      api_key = "catatan_user123:key:with:colons"

      assert {:ok, %Parse{id: "user123", key: "key:with:colons"}} = Parse.parse(api_key)
    end

    test "verifies struct fields are correctly populated" do
      api_key = "catatan_testid:testkey"

      assert {:ok, parsed} = Parse.parse(api_key)
      assert %Parse{} = parsed
      assert parsed.id == "testid"
      assert parsed.key == "testkey"
    end

    test "parses API key with Base64 encoded key" do
      api_key = "catatan_user123:dGVzdGtleQ=="

      assert {:ok, %Parse{id: "user123", key: "dGVzdGtleQ=="}} = Parse.parse(api_key)
    end
  end

  describe "parse/1 - invalid inputs" do
    test "returns error when missing catatan_ prefix" do
      api_key = "invalid_user123:key"

      assert {:error, :invalid_format} = Parse.parse(api_key)
    end

    test "returns error when missing colon separator" do
      api_key = "catatan_user123"

      assert {:error, :invalid_format} = Parse.parse(api_key)
    end

    test "returns error for empty string" do
      api_key = ""

      assert {:error, :invalid_format} = Parse.parse(api_key)
    end

    test "returns error for only catatan_ prefix without id and key" do
      api_key = "catatan_"

      assert {:error, :invalid_format} = Parse.parse(api_key)
    end

    test "returns error when only catatan prefix (no underscore)" do
      api_key = "catatan"

      assert {:error, :invalid_format} = Parse.parse(api_key)
    end

    test "returns error for completely invalid format" do
      api_key = "random_string"

      assert {:error, :invalid_format} = Parse.parse(api_key)
    end

    test "returns error when missing key part after colon" do
      api_key = "catatan_user123:"

      assert {:error, :invalid_format} = Parse.parse(api_key)
    end

    test "returns error when missing id part before colon" do
      api_key = "catatan_:key"

      assert {:error, :invalid_format} = Parse.parse(api_key)
    end

    test "returns error for api key starting with catatan but wrong separator" do
      api_key = "catatan-user123:key"

      assert {:error, :invalid_format} = Parse.parse(api_key)
    end
  end

  describe "integration with Generate module" do
    test "can parse API key generated by Generate.generate_api_key/2" do
      alias CatatanBackend.ApiKey.Generate

      id = "user123"
      key = "randomkey456"
      generated = Generate.generate_api_key(id, key)

      assert {:ok, parsed} = Parse.parse(generated)
      assert parsed.id == id
      assert parsed.key == key
    end

    test "round-trip with random key" do
      alias CatatanBackend.ApiKey.Generate

      id = "testuser"
      random_key = Generate.generate_random_key()
      generated = Generate.generate_api_key(id, random_key)

      assert {:ok, parsed} = Parse.parse(generated)
      assert parsed.id == id
      assert parsed.key == random_key
    end

    test "multiple round-trips produce correct results" do
      alias CatatanBackend.ApiKey.Generate

      test_cases = [
        {"user1", "key1"},
        {"user_2", "key_2"},
        {"user@3", "key$3"},
        {"123", "abc"}
      ]

      for {id, key} <- test_cases do
        generated = Generate.generate_api_key(id, key)
        assert {:ok, parsed} = Parse.parse(generated)
        assert parsed.id == id
        assert parsed.key == key
      end
    end
  end
end
